//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ExampleModule {
  public static int multiplication(int a, int b) {
    int ret = ExampleModulePINVOKE.multiplication(a, b);
    return ret;
  }

  public static void hello() {
    ExampleModulePINVOKE.hello();
  }

}
